name: "Protocol Buffer Go Stubs Generation"

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["roles", "users"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "Generate for Golang"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/run.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./run.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com
